---
- name: Developer Config playbook
  hosts: all
  become: true
  tasks:

    - name: Ensure GPG check is globally deactivated (yum)
      ini_file:
        dest: /etc/yum.conf
        section: main
        option: gpgcheck
        value: "{{ 0 | int }}"
        create: false
      register: stig
