---
- name: Security Compliance Remediation Playbook
  hosts: all
  become: true
  tasks:

    - name: Ensure dependencies installed
      package:
        name: python3-pip
        state: present

    - name: Ensure pysnow module is installed
      pip:
        executable: pip3
        name: pysnow
        state: present

    - name: Ensure GPG check is globally activated (yum)
      ini_file:
        dest: /etc/yum.conf
        section: main
        option: gpgcheck
        value: "{{ 1 | int }}"
        create: false
      register: stig

    - name: Create a change request
#      delegate_to: localhost
      check_mode: no
      become: false
      snow_record:
        state: present
#        table: change_request
        username: "{{ snow.username }}"
        password: "{{ snow.password }}"
        instance: "{{ snow.instance }}"
        data:
          severity: "{{ snow.severity }}"
          priority: "{{ snow.priority }}"
#          category: "{{ snow.category }}"
          comments: "Automated Scan results from Ansible Tower"
          short_description: "System out of compliance with STIGS"
          work_notes: "System {{ ansible_fqdn }} out of compliance with STIGs"
      register: new_incident
      when: ansible_check_mode and stig.changed

    - debug: 
        var: new_incident.record
      when: new_incident.changed
